[project]
name = "splart"
description = "SplArt: Articulation Estimation and Reconstruction with 3D Gaussian Splatting."
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]
include = ["splart"]

[project.entry-points.'nerfstudio.method_configs']
splart = 'splart.method_config:splart_method'

[project.entry-points.'nerfstudio.dataparser_configs']
splart-dataparser = 'splart.dataparser_config:splart_dataparser'

[tool.black]
line-length = 120
target-version = ["py311"]
skip-magic-trailing-comma = true
extend-exclude = '''
(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist|node_modules|.*_pb2.py|.*_pb2_grpc.py)
'''

[tool.isort]
profile = "black"
line_length = 120
